cd archive_builder
PASSWORD=""
APPLICATION_ID=""
BUILD_FOR_DEBUG=""
if [ -z "$1" ]
  then
    echo 'Please enter The Super User password'
    read -s PASSWORD
  else
    PASSWORD="$1"
fi

if [ -z "$2" ]
  then
    echo 'Please enter bundle or package or application id (Ex: robinhood.flutter.ota)'
    read APPLICATION_ID
  else
    APPLICATION_ID="$2"
fi

if [ -z "$3" ]
  then
    echo 'Enable UI debugger ? (y/n)'
    read BUILD_FOR_DEBUG
  else
    BUILD_FOR_DEBUG="$3"
fi

if [ -z "$4" ]
  then
    echo 'Enable UI performance tester ? (y/n)'
    read ENABLE_PERFORMANCE_TESTER
  else
    ENABLE_PERFORMANCE_TESTER="$4"
fi

echo  "App Id : ${APPLICATION_ID}"
echo "${PASSWORD}" | sudo -S rm -R gitdata
echo "${PASSWORD}" | sudo -S  rm -R build
echo "${PASSWORD}" | sudo -S  chmod a+rwx run.sh
#git clone https://github.com/nikhilishwarkulal/module_structure.git ./gitdata/
git clone -b feature/flutter_module https://gitlab.com/scbtechx/techx-ota/frontend/scb-ota-app.git ./gitdata/
mkdir ./gitdata/temp
cp ./gitdata/flutter_module/.android/build.gradle ./gitdata/temp/build.gradle
#mkdir gitdata && cd $_
#flutter create -t module --org $APPLICATION_ID flutter_module
#cd ..
rm -rf ./gitdata/flutter_module/lib
cp -R ../lib ./gitdata/flutter_module/lib
rm ./gitdata/flutter_module/lib/core_components/ota_channel/ota_channel_config.dart
rm -rf ./gitdata/flutter_module/test
echo "
///Auto generated by Script
class OtaChannelConfig {
  static bool isModule = true;
}" > ./gitdata/flutter_module/lib/core_components/ota_channel/ota_channel_config.dart
rm -rf ./gitdata/flutter_module/assets
cp -R ../assets ./gitdata/flutter_module/assets
rm -rf ./gitdata/flutter_module/pubspec.yaml
cp  ../pubspec.yaml ./gitdata/flutter_module/pubspec.yaml
echo "" >> ./gitdata/flutter_module/pubspec.yaml
echo "  module:" >> ./gitdata/flutter_module/pubspec.yaml
echo "    androidX: true" >> ./gitdata/flutter_module/pubspec.yaml
echo "    androidPackage: ${APPLICATION_ID}" >> ./gitdata/flutter_module/pubspec.yaml
echo "    iosBundleIdentifier: ${APPLICATION_ID}" >> ./gitdata/flutter_module/pubspec.yaml
mkdir build
mkdir build/ios
mkdir build/android
echo "${PASSWORD}" | sudo -S  chmod -R a+rwx ../archive_builder
cd gitdata
cd flutter_module
flutter clean
flutter pub get
cd .ios
pod install
cd ..
mv ../temp/build.gradle .android/build.gradle
#flutter build ios-framework --xcframework --no-profile --output=../../build/ios/
flutter build ios-framework --output=../../build/ios/ --dart-define=ENABLE_PERFORMANCE_TESTER=$ENABLE_PERFORMANCE_TESTER --dart-define=BUILD_FOR_DEBUG=$BUILD_FOR_DEBUG --dart-define=GRAPHQL_BASE_URL_DEV=https://ota-api-interface-dev.np.scbtechx.io --dart-define=GRAPHQL_BASE_URL_ALPHA=https://ota-api-interface-alpha.np.scbtechx.io --dart-define=GRAPHQL_BASE_URL_PROD=https://ota-api-interface.scbtechx.io --dart-define=GRAPHQL_BASE_URL_PT=https://ota-api-interface-pt.np.scbtechx.io --dart-define=GRAPHQL_BASE_URL_STAGING=https://ota-api-interface-staging.np.scbtechx.io --dart-define=GRAPHQL_BASE_URL_PREPROD=https://ota-api-interface-preprod.np.scbtechx.io
echo "${PASSWORD}" | sudo -S  flutter build aar --dart-define=ENABLE_PERFORMANCE_TESTER=$ENABLE_PERFORMANCE_TESTER --dart-define=BUILD_FOR_DEBUG=$BUILD_FOR_DEBUG --dart-define=GRAPHQL_BASE_URL_DEV=https://ota-api-interface-dev.np.scbtechx.io --dart-define=GRAPHQL_BASE_URL_ALPHA=https://ota-api-interface-alpha.np.scbtechx.io --dart-define=GRAPHQL_BASE_URL_PROD=https://ota-api-interface.scbtechx.io --dart-define=GRAPHQL_BASE_URL_PT=https://ota-api-interface-pt.np.scbtechx.io --dart-define=GRAPHQL_BASE_URL_STAGING=https://ota-api-interface-staging.np.scbtechx.io --dart-define=GRAPHQL_BASE_URL_PREPROD=https://ota-api-interface-preprod.np.scbtechx.io
cp -R build/host/outputs/repo ../../build/android/repo
echo "${PASSWORD}" | sudo -S  rm -rf ../../gitdata
