import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/mockito.dart';
import 'package:ota/core_pack/graphql/jwt_decoder.dart';
import 'package:shared_preferences/shared_preferences.dart';

class MockedSharedPreferences extends Mock implements SharedPreferences {}

void main() {
  test('JWT Decoder Test ...', () async {
    String accessToken =
        "eyJraWQiOiJmazRSXC9rYzBnWEplY0ZKRmVyUEdHSkVwamxkaFhUSWZGelFHNUl1MktnST0iLCJhbGciOiJSUzI1NiJ9.eyJvcmlnaW5fanRpIjoiMjRjODkxMDEtYmVhZi00N2U1LWIwOGEtY2Q4OWI1NGE4MDVhIiwic3ViIjoiNDAzOGYzMWUtY2Y2Mi00MzAxLTg2YTEtOGY1YzU2MmI5OWRkIiwiZXZlbnRfaWQiOiIyOGRhMGNiMS0xMGU5LTQ2NjUtYWEwOC1lMjM4OGU4Y2I3OGQiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6ImF3cy5jb2duaXRvLnNpZ25pbi51c2VyLmFkbWluIiwiYXV0aF90aW1lIjoxNjM3NzYyNjE3LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuYXAtc291dGhlYXN0LTEuYW1hem9uYXdzLmNvbVwvYXAtc291dGhlYXN0LTFfNHdIUXdNUDN2IiwiZXhwIjoxNjM3NzkxNDE3LCJpYXQiOjE2Mzc3NjI2MTcsImp0aSI6IjNiMGEzODViLTgyODktNDgzYS05YzZhLTQ0MTExYWNkYmEyZSIsImNsaWVudF9pZCI6IjFnc2M2a24zZGZ1MWkwN2s3cHE0djRyY2JyIiwidXNlcm5hbWUiOiJjYTA1MWJkZC1hMGRmLTQwNzQtYTFkOC05Y2IyMWIxYzc1YWQtNlRUU1ByaW4ifQ.TA52TpXXBPvwSZzl61bUd3EyW2xMXQcXOMT6eMWLXEqe7IsFkpNCTq8nNHc7YFCYL2dHnN8NLIpgDpwUmcp1IhZKLeR4mU7V1mMLu6z-JXoQKNqS_2EKAB8uecCTzlCVJLdctmxzNteebiuo_3IG3pQg4jtEFMspSVep-8MUr9yRLrGwnlM5FltL9QdOOFmuPtvNCp92PcabJgMo0z-75igr7nD7z4fPcEe3pfygmogLWkrScMxo0-t1dy1Jhi8ANeyKMVfKtlTBq5JZcUBesDS_7kGdp-5wmaetyr2sLn-JMbYTyHvuJAfKMsLvWoXK7RpueK_maMRvmsMS6Ginhw";
    expect(JwtDecoder.isExpired(accessToken), true);
  });
}
